/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminDevRouteImport } from './routes/admin-dev'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImportDrawsRouteImport } from './routes/api/import-draws'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevRoute = AdminDevRouteImport.update({
  id: '/admin-dev',
  path: '/admin-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportDrawsRoute = ApiImportDrawsRouteImport.update({
  id: '/api/import-draws',
  path: '/api/import-draws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin-dev': typeof AdminDevRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/terminal': typeof TerminalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/import-draws': typeof ApiImportDrawsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin-dev': typeof AdminDevRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/terminal': typeof TerminalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/import-draws': typeof ApiImportDrawsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin-dev': typeof AdminDevRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/terminal': typeof TerminalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/import-draws': typeof ApiImportDrawsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin-dev'
    | '/auth'
    | '/billing'
    | '/terminal'
    | '/api/chat'
    | '/api/import-draws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin-dev'
    | '/auth'
    | '/billing'
    | '/terminal'
    | '/api/chat'
    | '/api/import-draws'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin-dev'
    | '/auth'
    | '/billing'
    | '/terminal'
    | '/api/chat'
    | '/api/import-draws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminDevRoute: typeof AdminDevRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  TerminalRoute: typeof TerminalRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImportDrawsRoute: typeof ApiImportDrawsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dev': {
      id: '/admin-dev'
      path: '/admin-dev'
      fullPath: '/admin-dev'
      preLoaderRoute: typeof AdminDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-draws': {
      id: '/api/import-draws'
      path: '/api/import-draws'
      fullPath: '/api/import-draws'
      preLoaderRoute: typeof ApiImportDrawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminDevRoute: AdminDevRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  TerminalRoute: TerminalRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImportDrawsRoute: ApiImportDrawsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
