// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfzgjgkdbblysdslensu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmemdqZ2tkYmJseXNkc2xlbnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0Nzg5NDEsImV4cCI6MjA5NjA1NDk0MX0.hFxKypGu_6fSg-UcljCMu6gST1dFi1Z2ttDxLp_Lans";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});